-- Stickerpassi shop schema.
-- This mirrors the schema already applied to the linked Supabase project.

create table if not exists public.shop_products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  price_cents integer not null check (price_cents > 0),
  image_url text,
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_settings (
  id boolean primary key default true check (id = true),
  shipping_cents integer not null default 150 check (shipping_cents >= 0),
  free_shipping_threshold_cents integer check (free_shipping_threshold_cents is null or free_shipping_threshold_cents >= 0),
  currency text not null default 'EUR' check (currency = 'EUR'),
  updated_at timestamptz not null default now()
);

insert into public.shop_settings (id, shipping_cents, free_shipping_threshold_cents)
values (true, 150, 2000)
on conflict (id) do nothing;

create table if not exists public.shop_orders (
  id uuid primary key default gen_random_uuid(),
  checkout_token uuid not null default gen_random_uuid() unique,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  full_name text not null,
  address_line1 text not null,
  address_line2 text,
  postal_code text not null,
  city text not null,
  province text,
  country text not null default 'IT',
  subtotal_cents integer not null check (subtotal_cents >= 0),
  shipping_cents integer not null check (shipping_cents >= 0),
  total_cents integer not null check (total_cents >= 0),
  currency text not null default 'EUR' check (currency = 'EUR'),
  status text not null default 'pending_payment'
    check (status in ('pending_payment','paid','canceled','refunded','fulfilled')),
  payment_provider text not null default 'satispay',
  payment_id text unique,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.shop_orders(id) on delete cascade,
  product_id uuid not null references public.shop_products(id),
  product_name text not null,
  unit_price_cents integer not null check (unit_price_cents > 0),
  quantity integer not null check (quantity > 0 and quantity <= 50),
  line_total_cents integer not null check (line_total_cents > 0)
);

create index if not exists shop_orders_user_id_idx
  on public.shop_orders(user_id);

create index if not exists shop_order_items_order_id_idx
  on public.shop_order_items(order_id);

create index if not exists shop_order_items_product_id_idx
  on public.shop_order_items(product_id);

alter table public.shop_products enable row level security;
alter table public.shop_settings enable row level security;
alter table public.shop_orders enable row level security;
alter table public.shop_order_items enable row level security;

drop policy if exists "shop products public read" on public.shop_products;
create policy "shop products public read"
on public.shop_products for select
to anon, authenticated
using (is_active = true);

drop policy if exists "shop settings public read" on public.shop_settings;
create policy "shop settings public read"
on public.shop_settings for select
to anon, authenticated
using (true);

drop policy if exists "shop users read own orders" on public.shop_orders;
create policy "shop users read own orders"
on public.shop_orders for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "shop users read own order items" on public.shop_order_items;
create policy "shop users read own order items"
on public.shop_order_items for select
to authenticated
using (
  exists (
    select 1 from public.shop_orders o
    where o.id = shop_order_items.order_id
      and o.user_id = (select auth.uid())
  )
);

create or replace function public.shop_finalize_paid_order(p_payment_id text)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.shop_orders%rowtype;
  v_item record;
begin
  select * into v_order
  from public.shop_orders
  where payment_id = p_payment_id
  for update;

  if not found then raise exception 'order_not_found'; end if;
  if v_order.status in ('paid','fulfilled') then return v_order.id; end if;
  if v_order.status <> 'pending_payment' then raise exception 'order_not_payable'; end if;

  for v_item in
    select product_id, quantity
    from public.shop_order_items
    where order_id = v_order.id
  loop
    update public.shop_products
    set stock = stock - v_item.quantity,
        updated_at = now()
    where id = v_item.product_id
      and stock >= v_item.quantity;

    if not found then raise exception 'insufficient_stock'; end if;
  end loop;

  update public.shop_orders
  set status = 'paid', paid_at = now(), updated_at = now()
  where id = v_order.id;

  return v_order.id;
end;
$$;

revoke all on function public.shop_finalize_paid_order(text) from public;
revoke all on function public.shop_finalize_paid_order(text) from anon;
revoke all on function public.shop_finalize_paid_order(text) from authenticated;
grant execute on function public.shop_finalize_paid_order(text) to service_role;
